# 指定语言环境
language: node_js
# 指定node_js版本
node_js: stable
# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
    - node_modules

# 指定博客源码分支，因人而异。hexo博客源码托管在独立repo则不用设置此项
branches:
  only:
    - hexo 

before_install:
  - npm install -g hexo-cli
  - export TZ='Asia/Shanghai'

# Start: Build Lifecycle
install:
  - npm install

script:
  - hexo clean
  - hexo generate

after_script:
  - git clone https://${GH_REF} .deploy_git  # GH_REF是最下面配置的仓库地址
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./public/   # 这一步之前的操作是为了保留master分支的提交记录，不然每次git init的话只有1条commit
  - cd ./public
  - git config --global user.name "IcyW"
  - git config --global user.email "hbj032215@yeah.net"
  - git add .
  - git commit -m "Icy's Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"  # 提交记录包含时间
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master  #Travis_Token是在Travis中配置环境变量的名称

env:
 global:
   - GH_REF: github.com/IcyW/IcyWiki.github.io.git